language: objective-c
osx_image: xcode8

env: IOS_DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=10.0"

rvm:
    2.2.5

script:
    - security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain
    - travis_retry xcodebuild -project travis-ci-xcode-8.xcodeproj -scheme travis-ci-xcode-8 -destination "$IOS_DESTINATION" build test
