language: objective-c
osx_image: xcode8

env: IOS_DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=10.0"

matrix:
  include:
    - osx_image: xcode7.3
      env: IOS_DESTINATION="platform=iOS Simulator,name=iPhone 6s"

rvm:
    2.2.5

cache:
    - bundler
    - cocoapods
before_install:
    - gem install xcpretty
script:
    - xcodebuild -project travis-ci-xcode-8.xcodeproj -scheme travis-ci-xcode-8 -destination "platform=iOS Simulator,name=$IOS_DEVICE,OS=$IOS_VERSION" build test
