language: objective-c
osx_image: xcode8

env: IOS_DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=10.0"

rvm:
    2.2.5

before_script:
    - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6 (9.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
    - echo $IOS_SIMULATOR_UDID
    - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID 
script:
    - security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain
    - security keychain-unlock
    - travis_retry xcodebuild -project travis-ci-xcode-8.xcodeproj -scheme travis-ci-xcode-8 -destination "$IOS_DESTINATION" build test
